import { BudgetVsActual, KPISummary } from "./types";

export function buildSlackMessage(
  reportType: string,
  kpi: KPISummary,
  budgetVsActual: BudgetVsActual[],
  month: string
) {
  const blocks: Record<string, unknown>[] = [
    {
      type: "header",
      text: { type: "plain_text", text: `Budget Report - ${month}` },
    },
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*Total Budget:*\n$${kpi.totalBudget.toLocaleString()} USDT` },
        { type: "mrkdwn", text: `*Total Spend:*\n$${kpi.totalSpend.toLocaleString()} USDT` },
        { type: "mrkdwn", text: `*Utilization:*\n${kpi.utilization.toFixed(1)}%` },
        { type: "mrkdwn", text: `*Flagged Txns:*\n${kpi.flaggedCount}` },
      ],
    },
    { type: "divider" },
  ];

  if (reportType === "monthly_summary" || reportType === "budget_alert") {
    const tableRows = budgetVsActual
      .filter((r) => r.allocated > 0 || r.actual > 0)
      .map((r) => {
        const name = r.departmentName.padEnd(22);
        const budget = `$${r.allocated.toLocaleString()}`.padStart(10);
        const actual = `$${r.actual.toLocaleString()}`.padStart(10);
        const pct = `${r.utilization.toFixed(0)}%`.padStart(5);
        return `${name}${budget}${actual}${pct}`;
      });

    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text:
          "*Department Breakdown*\n```\n" +
          "Department              Budget    Actual   Util\n" +
          "─".repeat(52) +
          "\n" +
          tableRows.join("\n") +
          "\n```",
      },
    });
  }

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Generated by Budget Dashboard | ${new Date().toLocaleString()}`,
      },
    ],
  });

  return { blocks };
}

export async function sendSlackWebhook(
  webhookUrl: string,
  message: { blocks: Record<string, unknown>[] }
): Promise<{ ok: boolean; error?: string }> {
  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(message),
    });
    if (!res.ok) {
      return { ok: false, error: `Slack returned ${res.status}` };
    }
    return { ok: true };
  } catch (err) {
    return { ok: false, error: String(err) };
  }
}
